# Generated by Django 5.2 on 2026-08-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.IntegerField(help_text='옛 dolfinrest_dolfinbox.id', null=True, unique=True)),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('area', models.IntegerField(null=True)),
                ('source', models.CharField(default='yolov5', max_length=30)),
                ('boxname', models.CharField(blank=True, db_index=True, default='', help_text='JTA### 개체명', max_length=100)),
                ('src_not_fin', models.BooleanField(default=False)),
                ('src_not_identifiable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.IntegerField(help_text='옛 dolfinrest_dolfinimage.id', null=True, unique=True)),
                ('path', models.CharField(help_text='사진 뿌리 기준 상대경로', max_length=300, unique=True)),
                ('obsdate', models.DateField(db_index=True, null=True)),
                ('exifdatetime', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['obsdate', 'path'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', '들이기'), ('crop', '크롭'), ('sam2', 'SAM2.1'), ('yolo', 'YOLO'), ('export', '내보내기'), ('train', '학습')], db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, default='', help_text='모델 id 또는 가중치 경로', max_length=300)),
                ('git_sha', models.CharField(blank=True, default='', max_length=40)),
                ('host', models.CharField(blank=True, default='', max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='크롭 뿌리 기준 상대경로', max_length=300)),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop', to='finseg.box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='finseg.image'),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.TextField(help_text='"x,y x,y ..." 원본 화소 좌표. 자르기 전')),
                ('area', models.IntegerField(null=True)),
                ('conf', models.FloatField(null=True)),
                ('base_line', models.TextField(blank=True, default='', help_text='"x,y x,y" 앞·뒤 삽입점')),
                ('base_partial', models.BooleanField(default=False, help_text='삽입점을 다 못 봤다')),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='finseg.box')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='finseg.run')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.CharField(choices=[('fin', '등지느러미'), ('fluke', '꼬리지느러미'), ('rostrum', '주둥이'), ('other', '기타'), ('none', '아무것도아님')], max_length=10)),
                ('verdict', models.CharField(blank=True, choices=[('ok', '통과'), ('fix', '교정 필요')], default='', help_text="cls='none' 이면 빈 값", max_length=10)),
                ('edges', models.CharField(blank=True, choices=[('both', '양날'), ('leading', '앞날만'), ('trailing', '뒷날만'), ('neither', '둘 다 가림')], default='', max_length=10)),
                ('polygon', models.TextField(blank=True, default='', help_text='위 윤곽 교정본. 없으면 마스크 그대로')),
                ('base_line', models.TextField(blank=True, default='', help_text='아래 직선 교정본. 없으면 제안 그대로')),
                ('base_partial', models.BooleanField(blank=True, help_text='사람의 판단. NULL 이면 제안 그대로', null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='finseg.box')),
                ('mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='finseg.mask')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['box', '-id'], name='finseg_revi_box_id_9271bf_idx'), models.Index(fields=['reviewer', '-id'], name='finseg_revi_reviewe_659153_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mask',
            index=models.Index(fields=['box', 'is_current'], name='finseg_mask_box_id_877ab7_idx'),
        ),
    ]
