# Generated by Django 5.2 on 2026-08-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0002_alter_review_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='edges',
            field=models.CharField(blank=True, choices=[('both', '양날'), ('leading', '앞날만'), ('trailing', '뒷날만'), ('tip', '끄트머리')], default='', max_length=10),
        ),
    ]
