# Generated by Django 5.2 on 2026-08-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0003_alter_review_edges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cls',
            field=models.CharField(choices=[('fin', '등지느러미'), ('fluke', '꼬리지느러미'), ('rostrum', '주둥이'), ('head', '머리'), ('body', '몸통'), ('bird', '새'), ('pectoral', '가슴지느러미'), ('other', '기타'), ('none', '아무것도아님')], max_length=10),
        ),
    ]
