# Generated by Django 5.2 on 2026-08-16 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0005_base_partial_which_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='base_run',
            field=models.ForeignKey(blank=True, help_text='base_line 을 채운 실행', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_masks', to='finseg.run'),
        ),
    ]
