# Generated by Django 5.2 on 2026-08-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0006_mask_base_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='facing',
            field=models.CharField(blank=True, choices=[('', '모름'), ('left', '앞이 왼쪽'), ('right', '앞이 오른쪽')], default='', help_text='밑동 두 점 중 앞(머리 쪽)이 어디인가', max_length=10),
        ),
    ]
