# Generated by Django 5.2 on 2026-08-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0009_alter_review_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='conf',
            field=models.FloatField(blank=True, help_text='검출기가 말한 확신. 옛 상자는 비어 있다', null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='run',
            field=models.ForeignKey(blank=True, help_text='이 상자를 낸 실행', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='finseg.run'),
        ),
        migrations.AlterField(
            model_name='box',
            name='source',
            field=models.CharField(db_index=True, default='yolov5', max_length=30),
        ),
        migrations.AlterField(
            model_name='run',
            name='kind',
            field=models.CharField(choices=[('import', '들이기'), ('crop', '크롭'), ('sam2', 'SAM2.1'), ('yolo', 'YOLO'), ('detect', '검출'), ('export', '내보내기'), ('train', '학습')], db_index=True, max_length=20),
        ),
    ]
