# Generated by Django 5.2 on 2026-08-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0010_box_conf_box_run_alter_box_source_alter_run_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True, default='')),
                ('src_name', models.CharField(blank=True, default='', help_text='옛 dolfinrest_dolfinbox.boxname', max_length=50)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='human', help_text='human · cluster:<run> …', max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='finseg.box')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identifications', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, help_text="NULL 이면 '이 개체가 아니다'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='finseg.individual')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['box', '-id'], name='finseg_iden_box_id_2febf8_idx'), models.Index(fields=['individual', '-id'], name='finseg_iden_individ_de9f1f_idx')],
            },
        ),
    ]
