# Generated by Django 5.2 on 2026-08-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0011_individual_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='rep',
            field=models.ForeignKey(blank=True, help_text='이 개체를 대표하는 상자(사진)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represents', to='finseg.box'),
        ),
    ]
