# Generated by Django 5.2 on 2026-08-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0012_individual_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='holding',
            field=models.BooleanField(default=False, help_text='개체가 아니라 보류함이다'),
        ),
    ]
