# Generated by Django 5.2 on 2026-08-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0013_individual_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='cls',
            field=models.CharField(blank=True, default='', help_text='엔진이 낸 묶음 분류 (fin·dolphin·nonfin)', max_length=10),
        ),
    ]
