# Generated by Django 5.2 on 2026-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0015_individual_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='별명 — 있는 개체만', max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(help_text='카탈로그 번호', max_length=50, unique=True),
        ),
    ]
