# Generated by Django 5.2 on 2026-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0017_identification_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='판정을 넣은 자리 (`gate.client_ip`)', null=True),
        ),
    ]
