# Generated by Django 5.2 on 2026-09-02 11:16
"""`식별 불가능` 자리를 만든다.

자리는 자료가 아니라 뼈대다 — 화면을 한 번도 안 연 기계에서도 있어야 한다
(`0015` 가 `지느러미 아님` 을 만든 것과 같은 이유). 화면의 `get_or_create`
는 뒷받침일 뿐이다.
"""
from django.db import migrations, models


def make_unid(apps, schema_editor):
    Individual = apps.get_model("finseg", "Individual")
    if not Individual.objects.filter(kind="unid").exists():
        Individual.objects.create(kind="unid", name="식별 불가능")


def back(apps, schema_editor):
    apps.get_model("finseg", "Individual").objects.filter(kind="unid").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0018_review_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='kind',
            field=models.CharField(blank=True, choices=[('', '개체'), ('hold', '임시보관함'), ('notfin', '지느러미 아님'), ('unid', '식별 불가능')], default='', help_text='비어 있으면 진짜 개체다', max_length=10),
        ),
        migrations.RunPython(make_unid, back),
    ]
