# Generated by Django 5.2 on 2026-09-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finseg', '0019_alter_individual_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='pred',
            field=models.IntegerField(blank=True, help_text='모델의 1위 개체 id', null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='pred_by',
            field=models.CharField(blank=True, default='', help_text='그 말을 한 모델 (`reid_pred` 가 적는다)', max_length=80),
        ),
        migrations.AddField(
            model_name='identification',
            name='pred_p',
            field=models.FloatField(blank=True, help_text='그 확률 (온도 보정 뒤)', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='source',
            field=models.CharField(default='human', help_text='human · bulk · bulk-x · suggest …', max_length=20),
        ),
    ]
